import fs from 'node:fs';

// Single source of truth for persona storage. The storage/ dir is generated by
// the setup project (auth.setup.ts)
export const STORAGE_DIR = 'tests/e2e/storage';
export const AUTHOR_STATE = `${STORAGE_DIR}/author.json`;
export const VISITOR_STATE = `${STORAGE_DIR}/visitor.json`;

// playwright treats this as anonymous (no cookies/origins).
export const ANON_STATE = { cookies: [], origins: [] };

export type Persona = { email: string; password: string; username: string };

// Read personas at RUNTIME only (inside beforeAll or a test) - never at module top level.
export function readPersonas(): { author: Persona; visitor: Persona } {
    return JSON.parse(fs.readFileSync(`${STORAGE_DIR}/personas.json`, 'utf-8'));
}