export const IconMap: Map<string, string> = new Map([
	['application/pdf', 'vscode-icons:file-type-pdf2'],
	['application/msword', 'vscode-icons:file-type-word'],
	[
		'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		'vscode-icons:file-type-word',
	],
	['application/vnd.ms-excel', 'vscode-icons:file-type-excel'],
	[
		'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
		'vscode-icons:file-type-excel',
	],
	['application/vnd.ms-powerpoint', 'vscode-icons:file-type-powerpoint'],
	[
		'application/vnd.openxmlformats-officedocument.presentationml.presentation',
		'vscode-icons:file-type-powerpoint',
	],
	['application/zip', 'vscode-icons:file-type-zip'],
	['application/x-rar-compressed', 'vscode-icons:file-type-zip'],
	['application/x-7z-compressed', 'vscode-icons:file-type-zip'],
	['application/x-tar', 'vscode-icons:file-type-zip'],
	['application/x-bzip2', 'vscode-icons:file-type-zip'],
	['application/x-gzip', 'vscode-icons:file-type-zip'],
	['application/x-7z-compressed', 'vscode-icons:file-type-zip'],
	['application/x-zip-compressed', 'vscode-icons:file-type-zip'],
	['image/jpeg', 'vscode-icons:file-type-image'],
	['image/png', 'vscode-icons:file-type-image'],
	['image/gif', 'vscode-icons:file-type-image'],
	['image/svg+xml', 'vscode-icons:file-type-image'],
	['image/bmp', 'vscode-icons:file-type-image'],
	['image/webp', 'vscode-icons:file-type-image'],
	['image/tiff', 'vscode-icons:file-type-image'],
	['image/x-icon', 'vscode-icons:file-type-image'],
	['video/mp4', 'vscode-icons:file-type-video'],
	['video/quicktime', 'vscode-icons:file-type-video'],
	['video/x-msvideo', 'vscode-icons:file-type-video'],
	['video/x-ms-wmv', 'vscode-icons:file-type-video'],
	['video/x-flv', 'vscode-icons:file-type-video'],
	['video/webm', 'vscode-icons:file-type-video'],
	['video/3gpp', 'vscode-icons:file-type-video'],
	['video/3gpp2', 'vscode-icons:file-type-video'],
	['video/ogg', 'vscode-icons:file-type-video'],
	['text/plain', 'vscode-icons:file-type-text'],
	['text/html', 'vscode-icons:file-type-html'],
	['text/css', 'vscode-icons:file-type-css'],
	['text/javascript', 'vscode-icons:file-type-js'],
	['text/typescript', 'vscode-icons:file-type-typescript'],
	['text/markdown', 'vscode-icons:file-type-markdown'],
	['text/csv', 'vscode-icons:file-type-csv'],
	['text/calendar', 'vscode-icons:file-type-calendar'],
	['text/vcard', 'vscode-icons:file-type-vcard'],
	['text/xml', 'vscode-icons:file-type-xml'],
	['text/yaml', 'vscode-icons:file-type-yaml'],
	['text/x-sql', 'vscode-icons:file-type-sql'],
	['text/x-java', 'vscode-icons:file-type-java'],
	['text/x-python', 'vscode-icons:file-type-python'],
	['text/x-scala', 'vscode-icons:file-type-scala'],
	['text/x-csharp', 'vscode-icons:file-type-csharp'],
	['text/x-c', 'vscode-icons:file-type-c'],
	['text/x-c++', 'vscode-icons:file-type-cpp'],
	['text/x-php', 'vscode-icons:file-type-php'],
	['application/json', 'vscode-icons:file-type-json'],
	['application/vnd.trolltech.linguist', 'vscode-icons:file-type-typescript'],
]);
